const LABELS = {
	"TRANSFER_HEADING": "Transfer",
	"TRANSFER_TITLE": "CONFIRM DETAILS",
	"TRANSFER_TO": "TO",
	"TRANSFER_AMOUNT": "AMOUNT",
	"TRANSFER_TAX": "TAX",
	"TRANSFER_FINAL_AMOUNT": "FINAL AMOUNT",
	"TRANSFER_BUTTON": "TRANSFER",
	"TRANSFER_SUCCESS": "Transaction Successful",
	"TRANSFER_TXNID": "TXN ID: ",
	"TRANSFER_FINISH": "YAY!",
};

export default LABELS;
